export const chestTricepsRows = [
  {
    name: "Incline DB Press",
    setsReps: "۳–۵ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۹۰–۱۲۰ث",
    note: "پرس اصلی برای بخش بالایی سینه",
    copyText: "Incline DB Press",
  },
  {
    name: "Machine/Barbell Flat Press",
    setsReps: "۳–۴ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۹۰–۱۲۰ث",
    note: "تمرکز بر فشار افقی روی کل سینه",
    copyText: "Machine/Barbell Flat Press",
  },
  {
    name: "Weighted/Assisted Dips",
    setsReps: "۲–۳ × ۸–۱۲",
    tempo: "3–1–1",
    rest: "~۹۰ث",
    note: "تأکید بر سینه، مخصوصاً بخش پایینی",
    copyText: "Weighted/Assisted Dips",
  },
  {
    name: "Cable Fly (High→Low/Mid)",
    setsReps: "۷ × ۱۰–۱۲",
    tempo: "کنترلی",
    rest: "۳۰–۴۵ث",
    note: "کشش کامل سینه؛ ست‌های FST-7 با استرچ بین‌ست",
    fst7: true,
    copyText: "Cable Fly (High→Low",
  },
  {
    name: "Rope Pushdown",
    setsReps: "۳–۴ × ۱۰–۱۵",
    tempo: "3–1–1",
    rest: "۴۵–۷۵ث",
    note: "ایزوله‌سازی مستقیم عضلات پشت بازو",
    copyText: "Rope Pushdown",
  },
  {
    name: "Overhead DB/Rope Ext",
    setsReps: "۲–۳ × ۱۰–۱۲",
    tempo: "3–1–1",
    rest: "۴۵–۷۵ث",
    note: "هدف‌گیری سرِ بلند تریسپس (کشش در دامنه)",
    copyText: "Overhead DB/Rope",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "هوازی پایدار ۲۰–۴۵ دقیقه طبق پلن هفتگی",
  },
];

export const backRearDeltsRows = [
  {
    name: "Wide-Grip Lat Pulldown",
    setsReps: "۳–۴ × ۸–۱۲",
    tempo: "3–1–1",
    rest: "~۹۰ث",
    note: "کشش عریض برای لت و پهنای پشت",
    copyText: "Wide-Grip Lat Pulldown",
  },
  {
    name: "Chest-Supported Row (T-bar/Row Machine)",
    setsReps: "۳–۴ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۹۰–۱۲۰ث",
    note: "پارو زدن ساپورت‌شده برای ضخامت",
    copyText: "Chest-Supported Row (T-bar/Row Machine)",
  },
  {
    name: "Seated Cable Row (Neutral)",
    setsReps: "۳ × ۸–۱۲",
    tempo: "3–1–1",
    rest: "۷۵–۹۰ث",
    note: "دامنه کامل برای تعادل در حجم پشت",
    copyText: "Seated Cable Row (Neutral)",
  },
  {
    name: "Single-Arm DB Row",
    setsReps: "۲–۳ × ۸–۱۲/هر سمت",
    tempo: "3–1–1",
    rest: "۷۵–۹۰ث",
    note: "تمرکز و تقارن دو سمت بدن",
    copyText: "Single-Arm DB Row",
  },
  {
    name: "Straight-Arm Pulldown",
    setsReps: "۷ × ۱۰–۱۲",
    tempo: "کنترلی",
    rest: "۳۰–۴۵ث",
    note: "کشش عمیق لت‌ها؛ ست‌های FST-7",
    fst7: true,
    copyText: "Straight-Arm Pulldown",
  },
  {
    name: "Face Pull",
    setsReps: "۲–۳ × ۱۲–۱۵",
    tempo: "2–1–1",
    rest: "۴۵–۷۵ث",
    note: "هدف‌گیری دلتوئید خلفی و عضلات تثبیت‌کننده شانه",
    copyText: "Face Pull",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "هوازی پایدار ۲۰–۴۵ دقیقه بر اساس هفته",
  },
];

export const legsHamGlutesCalvesRows = [
  {
    name: "Romanian Deadlift",
    setsReps: "۳–۴ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۱۲۰ث",
    note: "هیپ‌هینج برای همسترینگ؛ تمرکز بر فرم و پشت صاف",
    copyText: "Romanian Deadlift",
  },
  {
    name: "Lying/Seated Leg Curl",
    setsReps: "۳–۴ × ۱۰–۱۲",
    tempo: "3–1–1",
    rest: "۶۰–۷۵ث",
    note: "ایزوله همسترینگ؛ هفته ۴ آخرین ست Drop-set",
    copyText: "Lying/Seated Leg Curl",
  },
  {
    name: "Hip Thrust (BB/Machine)",
    setsReps: "۳–۴ × ۸–۱۲",
    tempo: "مکث بالا ۱ث",
    rest: "۹۰–۱۲۰ث",
    note: "تمرکز بر گلوت؛ مکث ۱ث در بالاترین دامنه",
    copyText: "Hip Thrust (BB/Machine)",
  },
  {
    name: "Bulgarian Split Squat",
    setsReps: "۲–۳ × ۸–۱۲/هر پا",
    tempo: "3–1–1",
    rest: "~۹۰ث",
    note: "بهبود تعادل و عمق حرکتی",
    copyText: "Bulgarian Split Squat",
  },
  {
    name: "Calf Raise (Seated/Donkey)",
    setsReps: "۷ × ۱۰–۱۲ یا ۴ × ۱۲–۱۵",
    tempo: "2–1–1",
    rest: "۳۰–۴۵ث (FST) / ۶۰–۷۵ث",
    note: "تقویت ساق؛ ست‌های FST-7 اختیاری",
    fst7: true,
    copyText: "Calf Raise (Seated/Donkey)",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "هوازی پایدار ۲۰–۴۵ دقیقه",
  },
];

export const shouldersBicepsCoreRows = [
  {
    name: "Seated DB Shoulder Press",
    setsReps: "۳–۴ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۹۰–۱۲۰ث",
    note: "پرس اصلی شانه‌ها",
    copyText: "Seated DB Shoulder Press",
  },
  {
    name: "Lateral Raise (DB/Cable)",
    setsReps: "۳ × ۱۲–۱۵",
    tempo: "2–1–1",
    rest: "۴۵–۶۰ث",
    note: "پیش‌خستگی لترال برای رشد بهتر",
    copyText: "Lateral Raise (DB/Cable)",
  },
  {
    name: "Lateral Raise – FST-7",
    setsReps: "۷ × ۱۰–۱۲",
    tempo: "کنترلی",
    rest: "۳۰–۴۵ث",
    note: "ست‌های کششی برای پمپاژ شدید شانه",
    fst7: true,
    copyText: "Lateral Raise – FST-7",
  },
  {
    name: "Rear Delt Machine / Reverse Peck-Deck",
    setsReps: "۲–۳ × ۱۲–۱۵",
    tempo: "2–1–1",
    rest: "۴۵–۷۵ث",
    note: "تمرکز بر دلتوئید خلفی",
    copyText: "Rear Delt Machine / Reverse Peck-Deck",
  },
  {
    name: "EZ-Bar Curl",
    setsReps: "۳ × ۸–۱۲",
    tempo: "3–1–1",
    rest: "۶۰–۹۰ث",
    note: "جلو بازوی اصلی با دامنه کنترل‌شده",
    copyText: "EZ-Bar Curl",
  },
  {
    name: "Incline DB Curl",
    setsReps: "۲–۳ × ۱۰–۱۲",
    tempo: "3–1–1",
    rest: "۶۰–۷۵ث",
    note: "کشش کامل جلو بازو در دامنه پایین",
    copyText: "Incline DB Curl",
  },
  {
    name: "Core Circuit",
    setsReps: "۸–۱۰ دقیقه",
    tempo: "—",
    rest: "استراحت کم",
    note: "تمرین هسته (Plank / Deadbug / Pallof) با استراحت حداقلی",
    copyText: "Core Circuit",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "هوازی پایدار ۲۰–۴۵ دقیقه",
  },
];

export const quadsCalvesRows = [
  {
    name: "Hack Squat یا Leg Press",
    setsReps: "۴–۵ × ۶–۱۲",
    tempo: "3–1–1",
    rest: "~۱۲۰ث",
    note: "فشار سنگین و کنترل‌شده روی کواد",
    copyText: "Hack Squat یا Leg Press",
  },
  {
    name: "Front Squat یا Goblet",
    setsReps: "۳ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۱۲۰ث",
    note: "اسکوات با تنه قائم برای کواد",
    copyText: "Front Squat یا Goblet",
  },
  {
    name: "Walking Lunges",
    setsReps: "۲–۳ × ۲۰–۳۰ قدم مجموع",
    tempo: "2–1–1",
    rest: "~۹۰ث",
    note: "لانج پویا برای استقامت و حجم پا",
    copyText: "Walking Lunges",
  },
  {
    name: "Leg Extension",
    setsReps: "۷ × ۱۰–۱۲",
    tempo: "کنترلی",
    rest: "۳۰–۴۵ث",
    note: "کشش کامل کواد؛ ست‌های FST-7 با استرچ بین‌ست",
    fst7: true,
    copyText: "Leg Extension",
  },
  {
    name: "Standing Calf Raise",
    setsReps: "۴ × ۱۰–۱۵",
    tempo: "2–1–1",
    rest: "۶۰–۷۵ث",
    note: "تمرکز بر ساق با مکث در بالاترین دامنه",
    copyText: "Standing Calf Raise",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "هوازی پایدار ۲۰–۴۵ دقیقه",
  },
];
