export const chestTricepsRows = [
  {
    name: "Incline DB Press",
    setsReps: "۳–۵ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۹۰–۱۲۰ث",
    note: "کمپاندِ اصلی",
    copyText: "Incline DB Press",
  },
  {
    name: "Machine/Barbell Flat Press",
    setsReps: "۳–۴ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۹۰–۱۲۰ث",
    note: "فشار افقی",
    copyText: "Machine/Barbell Flat Press",
  },
  {
    name: "Weighted/Assisted Dips",
    setsReps: "۲–۳ × ۸–۱۲",
    tempo: "3–1–1",
    rest: "~۹۰ث",
    note: "سینه‌محور",
    copyText: "Weighted/Assisted Dips",
  },
  {
    name: "Cable Fly (High→Low/Mid)",
    setsReps: "۷ × ۱۰–۱۲",
    tempo: "کنترلی",
    rest: "۳۰–۴۵ث",
    note: "کشش بین‌ست",
    fst7: true,
    copyText: "Cable Fly (High→Low",
  },
  {
    name: "Rope Pushdown",
    setsReps: "۳–۴ × ۱۰–۱۵",
    tempo: "3–1–1",
    rest: "۴۵–۷۵ث",
    note: "ایزولهٔ تریسپس",
    copyText: "Rope Pushdown",
  },
  {
    name: "Overhead DB/Rope Ext",
    setsReps: "۲–۳ × ۱۰–۱۲",
    tempo: "3–1–1",
    rest: "۴۵–۷۵ث",
    note: "سرِ بلندِ تریسپس",
    copyText: "Overhead DB/Rope",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "۲۰–۴۵د مطابق پلن هفتگی",
  },
];

export const backRearDeltsRows = [
  {
    name: "Wide-Grip Lat Pulldown",
    setsReps: "۳–۴ × ۸–۱۲",
    tempo: "3–1–1",
    rest: "~۹۰ث",
    note: "لتِ کششی",
    copyText: "Wide-Grip Lat Pulldown",
  },
  {
    name: "Chest-Supported Row (T-bar/Row Machine)",
    setsReps: "۳–۴ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۹۰–۱۲۰ث",
    note: "قایقیِ ساپورت",
    copyText: "Chest-Supported Row (T-bar/Row Machine)",
  },
  {
    name: "Seated Cable Row (Neutral)",
    setsReps: "۳ × ۸–۱۲",
    tempo: "3–1–1",
    rest: "۷۵–۹۰ث",
    note: "دامنه کامل",
    copyText: "Seated Cable Row (Neutral)",
  },
  {
    name: "Single-Arm DB Row",
    setsReps: "۲–۳ × ۸–۱۲/هر سمت",
    tempo: "3–1–1",
    rest: "۷۵–۹۰ث",
    note: "تمرکز و سیمتری",
    copyText: "Single-Arm DB Row",
  },
  {
    name: "Straight-Arm Pulldown",
    setsReps: "۷ × ۱۰–۱۲",
    tempo: "کنترلی",
    rest: "۳۰–۴۵ث",
    note: "کشش بین‌ست",
    fst7: true,
    copyText: "Straight-Arm Pulldown",
  },
  {
    name: "Face Pull",
    setsReps: "۲–۳ × ۱۲–۱۵",
    tempo: "2–1–1",
    rest: "۴۵–۷۵ث",
    note: "دلتوئید خلفی / کف دست رو به هم",
    copyText: "Face Pull",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "۲۰–۴۵د برحسب هفته",
  },
];

export const legsHamGlutesCalvesRows = [
  {
    name: "Romanian Deadlift",
    setsReps: "۳–۴ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۱۲۰ث",
    note: "هیپ‌هینج؛ پشت صاف",
    copyText: "Romanian Deadlift",
  },
  {
    name: "Lying/Seated Leg Curl",
    setsReps: "۳–۴ × ۱۰–۱۲",
    tempo: "3–1–1",
    rest: "۶۰–۷۵ث",
    note: "هفته ۴: ست آخر Drop-set ×1",
    copyText: "Lying/Seated Leg Curl",
  },
  {
    name: "Hip Thrust (BB/Machine)",
    setsReps: "۳–۴ × ۸–۱۲",
    tempo: "مکث بالا ۱ث",
    rest: "۹۰–۱۲۰ث",
    note: "گلوت‌محور",
    copyText: "Hip Thrust (BB/Machine)",
  },
  {
    name: "Bulgarian Split Squat",
    setsReps: "۲–۳ × ۸–۱۲/هر پا",
    tempo: "3–1–1",
    rest: "~۹۰ث",
    note: "تعادل و عمق",
    copyText: "Bulgarian Split Squat",
  },
  {
    name: "Calf Raise (Seated/Donkey)",
    setsReps: "۷ × ۱۰–۱۲ یا ۴ × ۱۲–۱۵",
    tempo: "2–1–1",
    rest: "۳۰–۴۵ث (FST) / ۶۰–۷۵ث",
    note: "FST-7 اختیاری برای ساق",
    fst7: true,
    copyText: "Calf Raise (Seated/Donkey)",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "۲۰–۴۵د برحسب هفته",
  },
];

export const shouldersBicepsCoreRows = [
  {
    name: "Seated DB Shoulder Press",
    setsReps: "۳–۴ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۹۰–۱۲۰ث",
    note: "پرس اصلی",
    copyText: "Seated DB Shoulder Press",
  },
  {
    name: "Lateral Raise (DB/Cable)",
    setsReps: "۳ × ۱۲–۱۵",
    tempo: "2–1–1",
    rest: "۴۵–۶۰ث",
    note: "پیش‌خستگی لترال",
    copyText: "Lateral Raise (DB/Cable)",
  },
  {
    name: "Lateral Raise – FST-7",
    setsReps: "۷ × ۱۰–۱۲",
    tempo: "کنترلی",
    rest: "۳۰–۴۵ث",
    note: "FST-7 + کشش بین‌ست",
    fst7: true,
    copyText: "Lateral Raise – FST-7",
  },
  {
    name: "Rear Delt Machine / Reverse Peck-Deck",
    setsReps: "۲–۳ × ۱۲–۱۵",
    tempo: "2–1–1",
    rest: "۴۵–۷۵ث",
    note: "دلتوئید خلفی",
    copyText: "Rear Delt Machine / Reverse Peck-Deck",
  },
  {
    name: "EZ-Bar Curl",
    setsReps: "۳ × ۸–۱۲",
    tempo: "3–1–1",
    rest: "۶۰–۹۰ث",
    note: "جلو بازو",
    copyText: "EZ-Bar Curl",
  },
  {
    name: "Incline DB Curl",
    setsReps: "۲–۳ × ۱۰–۱۲",
    tempo: "3–1–1",
    rest: "۶۰–۷۵ث",
    note: "کشش کامل",
    copyText: "Incline DB Curl",
  },
  {
    name: "Core Circuit",
    setsReps: "۸–۱۰ دقیقه",
    tempo: "—",
    rest: "استراحت کم",
    note: "Plank / Deadbug / Pallof",
    copyText: "Core Circuit",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "۲۰–۴۵د برحسب هفته",
  },
];

export const quadsCalvesRows = [
  {
    name: "Hack Squat یا Leg Press",
    setsReps: "۴–۵ × ۶–۱۲",
    tempo: "3–1–1",
    rest: "~۱۲۰ث",
    note: "سنگین / کنترلی",
    copyText: "Hack Squat یا Leg Press",
  },
  {
    name: "Front Squat یا Goblet",
    setsReps: "۳ × ۶–۱۰",
    tempo: "3–1–1",
    rest: "۱۲۰ث",
    note: "تنه قائم",
    copyText: "Front Squat یا Goblet",
  },
  {
    name: "Walking Lunges",
    setsReps: "۲–۳ × ۲۰–۳۰ قدم مجموع",
    tempo: "2–1–1",
    rest: "~۹۰ث",
    note: "گام‌های یکنواخت",
    copyText: "Walking Lunges",
  },
  {
    name: "Leg Extension",
    setsReps: "۷ × ۱۰–۱۲",
    tempo: "کنترلی",
    rest: "۳۰–۴۵ث",
    note: "FST-7 کواد + کشش بین‌ست",
    fst7: true,
    copyText: "Leg Extension",
  },
  {
    name: "Standing Calf Raise",
    setsReps: "۴ × ۱۰–۱۵",
    tempo: "2–1–1",
    rest: "۶۰–۷۵ث",
    note: "مکث بالا ۱ث",
    copyText: "Standing Calf Raise",
  },
  {
    name: "کاردیو LISS",
    setsReps: "طبق هفته",
    tempo: "—",
    rest: "—",
    note: "۲۰–۴۵د برحسب هفته",
  },
];
